steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/devcode-457115/laravel_app_db_postgres_stg:staging-$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/devcode-457115/laravel_app_db_postgres_stg:staging-$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'gcp-postgressql-docker',
      '--image', 'gcr.io/devcode-457115/laravel_app_db_postgres_stg:staging-$SHORT_SHA',
      '--region', 'us-east4',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '5432'
      ]

images:
  - gcr.io/devcode-457115/laravel_app_db_postgres_stg:staging-$SHORT_SHA